TechQwerty.BookStore/Components/TopBooksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Runtime.InteropServices;
using TechQwerty.BookStore.Repository;

namespace TechQwerty.BookStore.Components
{
    public class TopBooksViewComponent : ViewComponent
    {
        private readonly IBookRepository _bookRepository;

        public TopBooksViewComponent(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var books = await _bookRepository.GetTopBooksAsync();
            return View(books);
        }
    }
}

TechQwerty.BookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TechQwerty.BookStore.Models;
using TechQwerty.BookStore.Service;

namespace TechQwerty.BookStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUserService _userService;
        private readonly IEmailService _emailService;

        public HomeController(ILogger<HomeController> logger, IUserService userService, IEmailService emailService)
        {
            _logger = logger;
            _userService = userService;
            _emailService = emailService;
        }

        public async Task<ViewResult> Index()
        {
            // send test email
            //UserEmailOptions options = new UserEmailOptions
            //{
            //    ToEmails = new List<string>() { "test@test.com" },
            //    PlaceHolders = new List<KeyValuePair<string, string>>()
            //    {
            //        new KeyValuePair<string, string>("{{ UserName }}", "Olawale")
            //    }
            //};
            //await _emailService.SendTestEmail(options);

            var userId = _userService.GetUserId();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TechQwerty.BookStore/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home"; }

<section class="jumbotron text-center">
    <div class="container">
        <h1>Welcome to Book Store Application</h1>
        <p class="lead text-muted">
            You are welcome to our Book Store platform. We have all kind of book in store for your reading. 
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search Books</a>
        </p>
    </div>
</section>

<div class="py-5 bg-light">
    <div class="container">
        <h3>Top Books</h3>

        <vc:top-books></vc:top-books>

    </div>
</div>